
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Kchan",
  description: "Generated by create next app",
  icons:{
   icon: [
    {
     url:'/images/favicon.ico',
     href:'/images/favicon.ico',
    }
   ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className="bg-gradient-to-l from-slate-700 to-slate-500">
       {children}
      </body>
    </html>
  );
}
