import { Metadata } from 'next';
import  Link  from 'next/link';

export const metadata: Metadata = {
  title: "23Chan/Board:Random",
  description: "Generated by create next app",
};

export default function Layout({children} : {children: React.ReactNode}){ 
 return(
  <main className="">
      <nav className="flex justify-around gap-4 w-full font-bold fixed z-50 bg-black text-white">
       <Link href="/">Main</Link>
       <Link href="/b">/b/</Link>
      </nav>
  <div className="p-10">
   {children}
  </div>
  </main>
 );
} 

