import { Metadata } from 'next';
import  Link  from 'next/link';

export const metadata: Metadata = {
  title: "23Chan/Board:Random",
  description: "Generated by create next app",
};

export default function Layout({children} : {children: React.ReactNode}){ 
 return(
  <main className="">
  {/*DIV HILOS*/}
  <div className="flex flex-col">
       <nav className="fixed flex flex-col justify-center items-center gap-5 p-2 h-full font-bold z-50  text-white"
        style={{
                backgroundColor:"black"
        }}
       >
        <Link href="/" className="hover:text-red-600">[Main]</Link>
        <Link href="/b" className="hover:text-red-600">[/b]</Link>
       </nav>
   <div className="pt-5 pl-20">
    {children}
   </div>
  </div>
  </main>
 );
} 

